insert into tipomuestra(nombre,descripcion,nemo,estado,fecharegistro) values ('ASPIRADO TRAQUEAL','TB',NULL,1,43081.3796703356)
insert into tipomuestra(nombre,descripcion,nemo,estado,fecharegistro) values ('GANGLIO CERVICAL','-',NULL,1,43081.3814100347)
insert into tipomuestra(nombre,descripcion,nemo,estado,fecharegistro) values ('LAVADO BRONCOALVEOLAR','TB',NULL,1,43081.3842508102)
insert into tipomuestra(nombre,descripcion,nemo,estado,fecharegistro) values ('LAVADO BRONQUIAL','tb',NULL,1,43081.3849113079)
insert into tipomuestra(nombre,descripcion,nemo,estado,fecharegistro) values ('LÍQUIDO ARTICULAR','TB',NULL,1,43081.3862986921)
insert into tipomuestra(nombre,descripcion,nemo,estado,fecharegistro) values ('LÍQUIDO ASCÍTICO','TB',NULL,1,43081.3881305208)
insert into tipomuestra(nombre,descripcion,nemo,estado,fecharegistro) values ('LÍQUIDO PLEURAL','TB',NULL,1,43081.3896441319)
insert into tipomuestra(nombre,descripcion,nemo,estado,fecharegistro) values ('LÍQUIDO SINOVIAL','TB',NULL,1,43081.3902344097)
insert into tipomuestra(nombre,descripcion,nemo,estado,fecharegistro) values ('POST ASPIRADO BRONQUIAL','TB',NULL,1,43081.3907009606)
insert into tipomuestra(nombre,descripcion,nemo,estado,fecharegistro) values ('SECRECIÓN','TB',NULL,1,43081.3913414005)
insert into tipomuestra(nombre,descripcion,nemo,estado,fecharegistro) values ('SECRECIÓN BRONQUIAL','TB',NULL,1,43081.3917579861)
insert into tipomuestra(nombre,descripcion,nemo,estado,fecharegistro) values ('SECRECIÓN DE MAMAS','TB',NULL,1,43081.3919261574)
insert into tipomuestra(nombre,descripcion,nemo,estado,fecharegistro) values ('SECRECIÓN VAGINAL','TB',NULL,1,43081.3920390394)
insert into tipomuestra(nombre,descripcion,nemo,estado,fecharegistro) values ('OTRO','TB',NULL,1,43081.3926608449)





insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('86','1')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('86','2')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('86','4')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('86','6')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('86','11')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('86','13')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('86','14')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('86','16')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('86','17')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('86','19')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('86','20')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('86','21')

insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('87','1')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('87','2')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('87','4')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('87','6')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('87','11')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('87','13')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('87','14')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('87','16')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('87','17')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('87','19')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('87','20')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('87','21')

insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('88','1')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('88','2')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('88','4')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('88','6')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('88','11')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('88','13')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('88','14')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('88','16')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('88','17')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('88','19')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('88','20')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('88','21')

insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('89','1')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('89','2')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('89','4')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('89','6')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('89','11')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('89','13')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('89','14')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('89','16')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('89','17')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('89','19')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('89','20')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('89','21')


insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('90','1')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('90','2')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('90','4')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('90','6')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('90','11')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('90','13')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('90','14')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('90','16')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('90','17')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('90','19')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('90','20')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('90','21')

insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('91','1')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('91','2')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('91','4')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('91','6')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('91','11')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('91','13')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('91','14')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('91','16')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('91','17')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('91','19')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('91','20')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('91','21')

insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('92','1')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('92','2')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('92','4')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('92','6')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('92','11')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('92','13')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('92','14')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('92','16')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('92','17')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('92','19')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('92','20')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('92','21')

insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('93','1')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('93','2')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('93','4')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('93','6')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('93','11')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('93','13')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('93','14')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('93','16')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('93','17')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('93','19')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('93','20')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('93','21')

insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('94','1')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('94','2')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('94','4')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('94','6')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('94','11')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('94','13')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('94','14')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('94','16')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('94','17')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('94','19')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('94','20')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('94','21')

insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('95','1')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('95','2')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('95','4')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('95','6')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('95','11')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('95','13')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('95','14')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('95','16')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('95','17')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('95','19')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('95','20')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('95','21')

insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('96','1')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('96','2')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('96','4')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('96','6')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('96','11')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('96','13')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('96','14')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('96','16')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('96','17')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('96','19')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('96','20')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('96','21')

insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('97','1')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('97','2')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('97','4')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('97','6')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('97','11')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('97','13')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('97','14')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('97','16')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('97','17')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('97','19')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('97','20')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('97','21')

insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('98','1')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('98','2')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('98','4')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('98','6')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('98','11')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('98','13')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('98','14')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('98','16')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('98','17')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('98','19')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('98','20')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('98','21')

insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('99','1')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('99','2')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('99','4')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('99','6')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('99','11')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('99','13')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('99','14')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('99','16')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('99','17')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('99','19')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('99','20')
insert into TipoMuestraCriterioRechazo(idTipoMuestra,idCriterioRechazo) values ('99','21')